### ISSUE TITLE
Windows CI builds fail

### ISSUE THREAD

**Issue by Jegp** [norse/norse#354]
Currently, Windows CI build fails with the following message:

```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\torch\lib /LIBPATH:C:\hostedtoolcache\windows\Python\3.9.13\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.9.13\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.9.13\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_norse_op C:\Users\RUNNER~1\AppData\Local\Temp\tmpwnk3wpk7.build-temp\Release\norse/csrc/op.obj C:\Users\RUNNER~1\AppData\Local\Temp\tmpwnk3wpk7.build-temp\Release\norse/csrc/super.obj /OUT:C:\Users\RUNNER~1\AppData\Local\Temp\tmptwq9etp1.build-lib\norse_op.pyd /IMPLIB:C:\Users\RUNNER~1\AppData\Local\Temp\tmpwnk3wpk7.build-temp\Release\norse/csrc\norse_op.lib
     Creating library C:\Users\RUNNER~1\AppData\Local\Temp\tmpwnk3wpk7.build-temp\Release\norse/csrc\norse_op.lib and object C:\Users\RUNNER~1\AppData\Local\Temp\tmpwnk3wpk7.build-temp\Release\norse/csrc\norse_op.exp
  op.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
  op.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
  C:\Users\RUNNER~1\AppData\Local\Temp\tmptwq9etp1.build-lib\norse_op.pyd : fatal error LNK1120: 2 unresolved externals
  Traceback (most recent call last):
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 512, in link
      self.spawn([self.linker] + ld_args)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 521, in spawn
      return super().spawn(cmd, env=env)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1007, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 140, in run
      self._create_wheel_file(bdist_wheel)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 330, in _create_wheel_file
      files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 261, in _run_build_commands
      self._run_build_subcommands()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 288, in _run_build_subcommands
      self.run_command(name)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
      super().run_command(command)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
      self.build_extensions()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
      build_ext.build_extensions(self)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 573, in build_extension
      self.compiler.link_shared_object(
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 751, in link_shared_object
      self.link(
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-0m1n7e69\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 514, in link
      raise LinkError(msg)
  distutils.errors.LinkError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
  error: Support for editable installs via PEP 660 was recently introduced
  in `setuptools`. If you are seeing this error, please report to:
  
  https://github.com/pypa/setuptools/issues
  
  Meanwhile you can try the legacy behavior by setting an
  environment variable and trying to install again:
  
  SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for norse
ERROR: Could not build wheels for norse, which is required to install pyproject.toml-based projects
Failed to build norse
Error: Process completed with exit code 1.
```

**Comment by cpehle** [comment]
I think this is fixed now, right?
