### ISSUE TITLE
CIFAR example not working

### ISSUE THREAD

**Issue by emijan-kth** [norse/norse#369]
`python -m norse.task.cifar10`

results in the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/raid/home/emil/norse/lib/python3.10/site-packages/norse/task/cifar10.py", line 193, in <module>
    parser = pl.Trainer.add_argparse_args(parser)
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'
```

**Comment by 4iar** [comment]
The `pl.Trainer.add_argparse_args` function was removed in Lightning 2.0 (https://github.com/Lightning-AI/lightning/pull/16708).

Downgrading to Lightning 1.x (`pip install pytorch-lightning==1.9.5`) should solve the issue for you
